/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DetailPemainRouteImport } from './routes/detail-pemain'
import { Route as KlasemenRouteImport } from './routes/klasemen'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailPemainRoute = DetailPemainRouteImport.update({
  id: '/detail-pemain',
  path: '/detail-pemain',
  getParentRoute: () => rootRouteImport,
} as any)
const KlasemenRoute = KlasemenRouteImport.update({
  id: '/klasemen',
  path: '/klasemen',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/detail-pemain': typeof DetailPemainRoute
  '/klasemen': typeof KlasemenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/detail-pemain': typeof DetailPemainRoute
  '/klasemen': typeof KlasemenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/detail-pemain': typeof DetailPemainRoute
  '/klasemen': typeof KlasemenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/detail-pemain' | '/klasemen'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/detail-pemain' | '/klasemen'
  id: '__root__' | '/' | '/detail-pemain' | '/klasemen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DetailPemainRoute: typeof DetailPemainRoute
  KlasemenRoute: typeof KlasemenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detail-pemain': {
      id: '/detail-pemain'
      path: '/detail-pemain'
      fullPath: '/detail-pemain'
      preLoaderRoute: typeof DetailPemainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klasemen': {
      id: '/klasemen'
      path: '/klasemen'
      fullPath: '/klasemen'
      preLoaderRoute: typeof KlasemenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DetailPemainRoute: DetailPemainRoute,
  KlasemenRoute: KlasemenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
